name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build -t ranchimallfze/flosight:$(date +%s) .
    
    - name: Login to Dockerhub 
      run: sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASS }}
      
    - name: Push to Dockerhub 
      run: sudo docker push ranchimallfze/flosight:$(date +%s)
 
